name: mobile
description: A cryptocurrency mobile application built with Golang, Flutter, Ethereum, gRPC and more

publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc:
  flutter_bloc:
  grpc:
  protobuf_google:
  google_fonts:
  auto_route:
  flutter_local_notifications:
  flutter_staggered_grid_view:
  flutter_staggered_animations:
  shared_preferences:
  fluttericon:
  dartz:
  carousel_slider:
  shared_utils:
    git:
      url: git://github.com/quabynah-bilson/shared_utils.git
      ref: main
  lottie:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  auto_route_generator:
  flutter_native_splash:
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/anim/
