name: mobile
description: A cryptocurrency mobile application built with Golang, Flutter, Ethereum, gRPC and more

publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc:
  flutter_bloc:
  grpc:
  protobuf_google:
  google_fonts:
  auto_route:
  flutter_local_notifications:
  flutter_staggered_grid_view:
  flutter_staggered_animations:
  shared_preferences:
  fluttericon:
  dartz:
  carousel_slider:
  shared_utils:
    git:
      url: git://github.com/quabynah-bilson/shared_utils.git
      ref: main
  lottie:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  auto_route_generator:
  flutter_native_splash:
  flutter_launcher_icons:

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/icons/mobile.logo.png
  image_dark: assets/icons/mobile.logo.png
  icon_background_color: "#ffffff"
  color: "#ffffff"
  color_dark: "#ffffff"
  icon_background_color_dark: "#ffffff"
  web: false
  android_12:
    image: assets/icons/mobile.logo.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#ffffff"
    color_dark: "#ffffff"
    image_dark: assets/icons/mobile.logo.png

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/mobile.logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
  windows:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/anim/
